import { StoreConfig } from '../types/store';

export const PRESETS: Record<string, StoreConfig> = {
  hairdresser: {
    id: 'hairdresser',
    name: 'LUXE Hair Studio',
    tagline: 'Premium Grooming & Styling',
    bannerImage: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?auto=format&fit=crop&q=80&w=1920&h=600',
    primaryColor: '#1a1a1a',
    secondaryColor: '#f5f2ed',
    theme: 'minimalist',
    layout: 'calendar',
    modules: {
      type: 'service',
      items: [
        {
          id: 's1',
          name: 'Executive Cut',
          price: 65,
          duration: 45,
          availableHours: ['09:00', '10:00', '11:00', '14:00', '15:00'],
          description: 'A precision cut tailored to your face shape and style.',
          imageUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&q=80&w=800&h=800',
        },
        {
          id: 's2',
          name: 'Beard Sculpture',
          price: 35,
          duration: 30,
          availableHours: ['10:00', '11:00', '12:00', '16:00'],
          description: 'Define your look with our signature beard grooming.',
          imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=800&h=800',
        },
      ],
    },
    seo: {
      title: 'LUXE Hair Studio | Amsterdam',
      description: 'The finest barbershop experience in Amsterdam.',
    },
  },
  catsitter: {
    id: 'catsitter',
    name: 'Whisker Watchers',
    tagline: 'Loving care for your feline friends',
    bannerImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=1920&h=600',
    primaryColor: '#ff8a5c',
    secondaryColor: '#fff5f0',
    theme: 'playful',
    layout: 'calendar',
    modules: {
      type: 'service',
      items: [
        {
          id: 'c1',
          name: 'Daily Drop-in',
          price: 25,
          duration: 60,
          availableHours: ['08:00', '12:00', '18:00'],
          description: 'Feeding, play time, and litter box cleaning.',
          imageUrl: 'https://images.unsplash.com/photo-1517331156700-3c241d2b4d83?auto=format&fit=crop&q=80&w=800&h=800',
        },
        {
          id: 'c2',
          name: 'Overnight Stay',
          price: 55,
          duration: 720,
          availableHours: ['20:00'],
          description: 'Full night of company and cuddles for your cat.',
          imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800&h=800',
        },
      ],
    },
    seo: {
      title: 'Whisker Watchers | Expert Cat Sitting',
      description: 'Professional cat sitters you can trust.',
    },
  },
  tshirt: {
    id: 'tshirt',
    name: 'STREET CORE',
    tagline: 'Defined by the streets',
    bannerImage: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80&w=1920&h=600',
    primaryColor: '#00ff00',
    secondaryColor: '#000000',
    theme: 'streetwear',
    layout: 'grid',
    modules: {
      type: 'product',
      items: [
        {
          id: 't1',
          name: 'Cyber Grail Tee',
          price: 45,
          description: 'Heavyweight cotton with neon puff print.',
          imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800&h=800',
          isOutOfStock: false,
          variants: [
            {
              label: 'Size',
              options: ['S', 'M', 'L', 'XL'],
              inventory: { S: 10, M: 5, L: 0, XL: 2 },
            },
          ],
        },
        {
          id: 't2',
          name: 'Binary Hoodie',
          price: 85,
          description: 'Oversized fit with embroidered code detail.',
          imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800&h=800',
          isOutOfStock: false,
        },
      ],
    },
    seo: {
      title: 'STREET CORE | Streetwear Shop',
      description: 'Limited edition underground apparel.',
    },
  },
  artseller: {
    id: 'artseller',
    name: 'Obscura Gallery',
    tagline: 'Rare artifacts and fine art',
    bannerImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=1920&h=600',
    primaryColor: '#ffffff',
    secondaryColor: '#0a0a0a',
    theme: 'sophisticated',
    layout: 'grid',
    modules: {
      type: 'product',
      items: [
        {
          id: 'a1',
          name: 'Ethereal Motion #4',
          price: 1200,
          description: 'Original oil on canvas. Explores the duality of light.',
          imageUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800&h=1000',
          isOutOfStock: false,
        },
        {
          id: 'a2',
          name: 'Monolith Study',
          price: 850,
          description: 'Mixed media sculpture. Signed by the artist.',
          imageUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&q=80&w=800&h=1000',
          isOutOfStock: true,
        },
      ],
    },
    seo: {
      title: 'Obscura Gallery | Fine Art',
      description: 'Curation of contemporary masterpieces.',
    },
  },
  natural: {
    id: 'natural',
    name: 'Natural Studio',
    tagline: 'Grounded in Nature',
    bannerImage: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&q=80&w=1920&h=600',
    primaryColor: '#292524',
    secondaryColor: '#F7F6F2',
    theme: 'natural',
    layout: 'grid',
    modules: {
      type: 'product',
      items: [
        {
          id: 'n1',
          name: 'Stone Bowl',
          price: 45,
          description: 'Hand-carved from river stone.',
          imageUrl: 'https://images.unsplash.com/photo-1533281808624-e9b07b4294ff?auto=format&fit=crop&q=80&w=800&h=800',
          isOutOfStock: false,
        },
        {
          id: 'n2',
          name: 'Linen Throw',
          price: 120,
          description: 'Organic unbleached linen with fringed edges.',
          imageUrl: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800&h=800',
          isOutOfStock: false,
        },
      ],
    },
    seo: {
      title: 'Natural Studio | Artisanal Home',
      description: 'Sustainably sourced home goods.',
    },
  },
};
